jobs:
  run:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Pull Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./ci/test

name: Build

on:
  schedule:
    - cron: "10 0/3 * * *"
